# Generated by Django 2.1.2 on 2018-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180925_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
