# Generated by Django 2.1 on 2018-08-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Couple'), (2, 'Bridal Party'), (3, 'Family')])),
                ('description', models.TextField()),
            ],
        ),
    ]
