# Generated by Django 2.0.7 on 2018-08-05 04:02

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75)),
                ('username', models.SlugField(unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('family', models.CharField(choices=[('Tony', 'Tony'), ('Haya', 'Haya'), ('Friend', 'Friend')], max_length=6)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('administrative_area', models.CharField(max_length=60)),
                ('sub_administrative_area', models.CharField(max_length=60)),
                ('locality', models.CharField(max_length=60)),
                ('dependent_locality', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=20)),
                ('thoroughfare', models.CharField(max_length=60)),
                ('premise', models.CharField(max_length=60)),
                ('sub_premise', models.CharField(max_length=60)),
                ('lead_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='guests.Guest')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='guests.Guest')),
            ],
        ),
    ]
