# Generated by Django 2.1 on 2018-09-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_activity_rsvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'verbose_name': 'RSVP'},
        ),
    ]
