# Generated by Django 2.0.7 on 2018-08-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20180805_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('es', 'Spanish'), ('en', 'English')], max_length=2),
        ),
    ]
