# Generated by Django 2.1 on 2018-09-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20180925_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='lead_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='guests.Guest'),
        ),
    ]
