# Generated by Django 2.0.7 on 2018-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20180805_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('ar', 'Arabic'), ('en', 'English')], max_length=2),
        ),
    ]
