# Generated by Django 2.1 on 2018-09-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180925_0336'),
        ('guests', '0004_auto_20180927_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='lead',
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='guests.RSVP'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Payment'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='activities',
            field=models.ManyToManyField(related_name='groups', to='guests.Activity'),
        ),
    ]
