# Generated by Django 2.1 on 2018-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20180927_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='guests.RSVP'),
        ),
    ]
