# Generated by Django 2.1 on 2018-09-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20180927_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Payment'),
        ),
    ]
