# Generated by Django 2.0.7 on 2018-08-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_auto_20180805_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English'), ('ar', 'Arabic')], max_length=2),
        ),
    ]
