# Generated by Django 2.1 on 2018-09-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_auto_20180927_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
