# Generated by Django 2.1 on 2018-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_rsvp_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
