# Generated by Django 2.1 on 2018-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_auto_20180805_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=2),
        ),
    ]
