# Generated by Django 2.1 on 2018-10-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_auto_20180927_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='nights_onsite',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
