# Generated by Django 2.1 on 2018-10-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_auto_20181008_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='name',
        ),
    ]
