# Generated by Django 2.1 on 2018-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_auto_20180805_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('es', 'Spanish')], max_length=2),
        ),
    ]
