# Generated by Django 2.1 on 2018-08-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_auto_20180805_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('ar', 'Arabic'), ('en', 'English')], max_length=7),
        ),
    ]
