# Generated by Django 2.1 on 2018-10-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_auto_20181011_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Payment'),
        ),
    ]
