# Generated by Django 2.1.2 on 2018-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_auto_20181023_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invite_printed',
            field=models.BooleanField(default=False),
        ),
    ]
