# Generated by Django 2.1 on 2018-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180805_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='family',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bride'), (2, 'Groom'), (3, 'Friend')], null=True),
        ),
    ]
