# Generated by Django 2.1 on 2018-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_auto_20180806_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='family',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bride'), (2, 'Groom'), (3, 'Friend')], default=3),
        ),
    ]
