# Generated by Django 2.1 on 2018-08-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('guests', '0022_guest_kuwait_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='profile',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
            preserve_default='True',
        ),
    ]
