# Generated by Django 2.1 on 2018-09-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0024_auto_20180917_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='full_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
