# Generated by Django 2.1 on 2018-09-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_auto_20180917_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='guests.Guest'),
        ),
    ]
