# Generated by Django 2.1 on 2018-09-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0027_remove_guest_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='profile',
        ),
    ]
